#pragma once
#include <QtCore/qglobal.h>

#if defined(MISKEYED_WORKBENCH_SLANG_RHI_STATIC)
#define MISKEYED_WORKBENCH_SLANG_RHI_EXPORT
#elif defined(MISKEYED_WORKBENCH_SLANG_RHI_LIBRARY)
#define MISKEYED_WORKBENCH_SLANG_RHI_EXPORT Q_DECL_EXPORT
#else
#define MISKEYED_WORKBENCH_SLANG_RHI_EXPORT Q_DECL_IMPORT
#endif
